### ISSUE TITLE
tinterval / interval - minutes or seconds?

### ISSUE THREAD

**Issue by OliverWieland** [markweirath/b3-plugin-poweradminurt#10]
Please check the units of tinterval (teambalancer) and interval (skillbalancer): In XML there is a comment that they will be set in minutes; I'm pretty shure they will be set in seconds instead.

Greetings
Oli (|BL|BlumentopfErde)

**Comment by tomyl** [comment]
Hi,

I think it's actually in minutes, in the call to b3.cron.PluginCronTab seconds is set to zero and minutes to the 'interval' setting. I fixed the typo (tinterval) in my branch though.

/tomyl

**Comment by markweirath** [comment]
Thanks guys for your contribution.
This is greatly appreciated!
