### ISSUE TITLE
Error: could not handle event Game Round Start

### ISSUE THREAD

**Issue by OliverWieland** [markweirath/b3-plugin-poweradminurt#12]
In my Logfile there are many error messages:

120115 15:55:05 ERROR   "handler PoweradminurtPlugin could not handle event Game Round Start: UnboundLocalError: local variable 'time' referenced before assignment [('/home/urt/b3_live/b3/parser.py', 961, 'handleEvents', 'hfunc.parseEvent(event)'), ('/home/urt/b3_live/b3/plugin.py', 157, 'parseEvent', 'self.onEvent(event)'), ('/home/urt/b3_live/b3/extplugins/poweradminurt.py', 802, 'onEvent', 'self._lastbal = time.time()')]"

**Comment by markweirath** [comment]
A new branch was created to test fixes for this error.
https://github.com/xlr8or/b3-plugin-poweradminurt/tree/time-error

This branch is for you to test. I will keep this issue open for now until fix is confirmed.

**Comment by OliverWieland** [comment]
Ok, this seems to solve the error. No error message the whole day.
Thanks for fixing it!

**Comment by markweirath** [comment]
Can you also confirm that functionality is still intact?

**Comment by OliverWieland** [comment]
Yes, all seems to be ok.
