### ISSUE TITLE
Problem with _minbalinterval

### ISSUE THREAD

**Issue by OliverWieland** [markweirath/b3-plugin-poweradminurt#13]
Hi Mark,

_minbalinterval does have no effect.

Please change in cmd_paskuffle and cmd_pabalance the following line:

```
    if client.maxLevel < 20 and self.ignoreCheck() and sinceLast < 60*self._minbalinterval:
```

to

```
    if client and (client.maxLevel) < 20 and self.ignoreCheck() and (sinceLast < 60*self._minbalinterval):
```

The query of 'client' i got from tomyl's fork. The relevant changes are the brackets.

Regards
Oli

**Comment by markweirath** [comment]
Can you explain to me what the brackets wrapping (client.maxLevel) and (sinceLast < 60*self._minbalinterval) change in your opinion?

**Comment by OliverWieland** [comment]
Hmm, you are right, this makes no sense.
I thought, the operator "and" has a higher priority then "<"

The first brackets are absolute nonsense, I wanted to write "(client.maxLevel < 20)".

Oddly enough I had an issue with the original row, which were gone with the changed one ...
